Messages:
  Login: '&7[&4Login&7] &cPlease login with /login [password]'
  IPsaved: '&aAutomatically logged in.'
  Register: '&7[&4Login&7] &cPlease register with /register [password] [password]'
  LoginSucces: '&7[&2Login&7] &aYou successfully logged in.'
  AlreadyRegistered: '&7[&4Error&7] &cOops, it seems that you are already registered.'
  AlreadyLoggedIn: '&7[&4Error&7] &cYou are already logged in.'
  RegistrationSuccess: '&7[&2Login&7] &aSuccessfully registered!'
  ChoosenPW: '&7[&2Login&7] &aYour choosen password is &6'
  ChangePWUsage: '&7[&4Login&7] &cChange your password with /changepw [password] [password]'
  ChangeSuccess: '&7[&2Login&7] &aSuccessfull changed your password in '
  ChangeNotMatch: '&7[&4Login&7] &cYour new password doesnt match.'
  PwNotMatch: '&7[&4Login&7] &cYour password does not match.'
  HaveToLogin: '&7[&4Login&7] &cYou have to Login.'
  WrongLogin: '&7[&4Login&7] &cWrong password.'
  NotOnline: '&7[&4Login&7] &cThe player is not online.'
  NotPassword: '&7[&4Login&7] &cThe password can not be "password".'
  MinSix: '&7[&4Login&7] &cThe password must have at least 6 characters.'
AllowIPSaver: true
Check:
  Line1: '&cName:&6 '
  Line2: '&7Registered: &ayes'
  Line3: '&7Registered: &cno'
  Line4: '&7Online:&e '
  Line5: '&7Current Session Ip:&3 '
  Line6: '&7Password MD5:&6 '
  Usage: '&cUsage /check [player]'