Messages:
  Login: '&7[&4Login&7] &cPlease login with /login [password]'
  IPsaved: '&aAutomatically logged in.'
  Register: '&7[&4Login&7] &cPlease register with /register [password] [password]'
  LoginSucces: '&7[&2Login&7] &aYou successfully logged in.'
  AlreadyRegistered: '&7[&4Error&7] &cOops, it seems that you are already registered.'
  AlreadyLoggedIn: '&7[&4Error&7] &cYou are already logged in.'
  NotRegistered: '&7[&4Error&7] &cOops, it seems that the player you are trying to unregister is not registered.'
  RegistrationSuccess: '&7[&2Login&7] &aSuccessfully registered!'
  UnregistrationSuccess: '&7[&2Login&7] &aSuccessfully unregistered!'
  ChoosenPW: '&7[&2Login&7] &aYour choosen password is &6'
  ChangePWUsage: '&7[&4Login&7] &cChange your password with /changepw [password] [password]'
  ChangeSuccess: '&7[&2Login&7] &aSuccessfull changed your password in '
  ChangeNotMatch: '&7[&4Login&7] &cYour new password doesnt match.'
  PwNotMatch: '&7[&4Login&7] &cYour password does not match.'
  HaveToLogin: '&7[&4Login&7] &cYou have to Login.'
  WrongLogin: '&7[&4Login&7] &cWrong password.'
  NotPassword: '&7[&4Login&7] &cThe password can not be "password".'
  MinSix: '&7[&4Login&7] &cThe password must have at least 6 characters.'
  IpReach: '&7[&4Login&7] &cYou have already registered enough accounts on this server.'
  Error: '&7[&4Error&7] &cGeneric Error - See the console for more details.'
  KickName: 'Your name contains illegal characters.'
  IllegalPassword: '&7[&4Error&7] &cYour password contains illegal characters.'
  NicknameCharacters: '[a-zA-Z0-9_]*'
  PasswordCharacters: '[!-~]*'
AllowIPSaver: true
QuitKeepAlive: 120
AccountNumber: 2
Check:
  Line1: '&cName:&6 '
  Line2: '&7Registered: &ayes'
  Line3: '&7Registered: &cno'
  Line4: '&7Online:&e '
  Line5: '&7Registration Ip:&3 '
  Line6: '&7Current Session Ip:&3 '
  Line7: '&7Password MD5:&6 '
  Usage: '&cUsage /check [player]'