name: LoginReloaded
version: 1.3
description: Add the login functionality to a Bukkit server.
author: 8bitFra
main: fra.plugin.login.Main

commands:
  login:
    description: Login your account.
    permission: loginreloaded.registration
    permission-message: You do not have permission to use this command!
  register:
    description: Register your account.
    permission: loginreloaded.registration
    permission-message: You do not have permission to use this command!
  logout:
    description: Logout your account.
    permission: loginreloaded.registration
    permission-message: You do not have permission to use this command!
  unregister:
    description: Delete a specific user's password.
    permission: loginreloaded.resetpw
    permission-message: You do not have permission to use this command!
  changepw:
    description: Change your login password.
    permission: loginreloaded.changepw
    permission-message: You do not have permission to use this command!
  check:
    description: Get some useful informations of a user.
    permission: loginreloaded.check
    permission-message: You do not have permission to use this command!
    

permissions:
  loginreloaded.registration:
    description: Allows you to use the /register - /login - /logout commands.
    default: true
  loginreloaded.unregister:
    description: Allows you to use the /unregister command.
    default: op
  loginreloaded.changepw:
    description: Allows you to use the /changepw command.
    default: true
  loginreloaded.check:
    description: Allows you to use the /check command.
    default: op